### **Build a regression model with Keras**

#### **A. Creating baseline model**

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input
from sklearn.model_selection import train_test_split

In [2]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

In [3]:
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
# Create X and y (features and labels)
X = concrete_data.drop("Strength", axis=1)
y = concrete_data["Strength"]

In [8]:
# View X
X.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
# View y
y.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
# Splitting data into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
len(X), len(X_train), len(X_test)

(1030, 721, 309)

In [11]:
# Create a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

In [12]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Train and test the model at the same time
    res = model.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 144.7666473388672
Cycle #2: mean_squared_error 119.5103759765625
Cycle #3: mean_squared_error 111.17548370361328
Cycle #4: mean_squared_error 105.7327651977539
Cycle #5: mean_squared_error 110.7430191040039
Cycle #6: mean_squared_error 107.98838806152344
Cycle #7: mean_squared_error 101.95978546142578
Cycle #8: mean_squared_error 116.21357727050781
Cycle #9: mean_squared_error 80.99010467529297
Cycle #10: mean_squared_error 72.45655822753906
Cycle #11: mean_squared_error 69.4825668334961
Cycle #12: mean_squared_error 69.41679382324219
Cycle #13: mean_squared_error 63.2273063659668
Cycle #14: mean_squared_error 62.11308288574219
Cycle #15: mean_squared_error 59.61676025390625
Cycle #16: mean_squared_error 59.02305603027344
Cycle #17: mean_squared_error 58.47664260864258
Cycle #18: mean_squared_error 55.28010940551758
Cycle #19: mean_squared_error 55.35075759887695
Cycle #20: mean_squared_error 49.393062591552734
Cycle #21: mean_squared_error 49.78382873535156
Cycle #22: mean_squared_error 51.29628372192383
Cycle #23: mean_squared_error 57.514129638671875
Cycle #24: mean_squared_error 48.441184997558594
Cycle #25: mean_squared_error 49.57273864746094
Cycle #26: mean_squared_error 48.565040588378906
Cycle #27: mean_squared_error 60.886558532714844
Cycle #28: mean_squared_error 52.12184524536133
Cycle #29: mean_squared_error 49.67719650268555
Cycle #30: mean_squared_error 54.421173095703125
Cycle #31: mean_squared_error 50.50204849243164
Cycle #32: mean_squared_error 48.57576370239258
Cycle #33: mean_squared_error 54.96078872680664
Cycle #34: mean_squared_error 52.47568130493164
Cycle #35: mean_squared_error 54.181549072265625
Cycle #36: mean_squared_error 63.755306243896484
Cycle #37: mean_squared_error 48.782875061035156
Cycle #38: mean_squared_error 48.822017669677734
Cycle #39: mean_squared_error 58.112274169921875
Cycle #40: mean_squared_error 48.688087463378906
Cycle #41: mean_squared_error 51.48616027832031
Cycle #42: mean_squared_error 57.99821472167969
Cycle #43: mean_squared_error 61.27378463745117
Cycle #44: mean_squared_error 61.319583892822266
Cycle #45: mean_squared_error 51.29276657104492
Cycle #46: mean_squared_error 49.22276306152344
Cycle #47: mean_squared_error 50.133968353271484
Cycle #48: mean_squared_error 49.4756965637207
Cycle #49: mean_squared_error 52.641380310058594
Cycle #50: mean_squared_error 61.117027282714844

In [13]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 65.40029121398926
The standard deviation of the mean squared errors: 23.132115564776328

#### **B. Normalize the data**

In [14]:
X_norm = (X - X.mean())/X.std()
X_norm.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
5,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,0.701883
6,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
7,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597
8,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,-0.279597
9,1.854740,-0.856472,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597

In [15]:
# Create a model
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model_2.compile(optimizer='adam', loss='mean_squared_error')

In [16]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Splitting data into training set and test set
    X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3)
    #Train and test the model at the same time
    res = model_2.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 455.60980224609375
Cycle #2: mean_squared_error 150.6235809326172
Cycle #3: mean_squared_error 114.4305648803711
Cycle #4: mean_squared_error 88.17723083496094
Cycle #5: mean_squared_error 64.32269287109375
Cycle #6: mean_squared_error 55.37126922607422
Cycle #7: mean_squared_error 51.237003326416016
Cycle #8: mean_squared_error 49.92914962768555
Cycle #9: mean_squared_error 44.66703414916992
Cycle #10: mean_squared_error 43.922828674316406
Cycle #11: mean_squared_error 47.19723129272461
Cycle #12: mean_squared_error 40.47425842285156
Cycle #13: mean_squared_error 39.83116149902344
Cycle #14: mean_squared_error 40.1787109375
Cycle #15: mean_squared_error 35.89670181274414
Cycle #16: mean_squared_error 39.57476806640625
Cycle #17: mean_squared_error 35.07663345336914
Cycle #18: mean_squared_error 34.45836639404297
Cycle #19: mean_squared_error 33.93509292602539
Cycle #20: mean_squared_error 32.28630065917969
Cycle #21: mean_squared_error 33.756378173828125
Cycle #22: mean_squared_error 37.68721008300781
Cycle #23: mean_squared_error 35.64997100830078
Cycle #24: mean_squared_error 38.071624755859375
Cycle #25: mean_squared_error 32.28952407836914
Cycle #26: mean_squared_error 35.546226501464844
Cycle #27: mean_squared_error 35.04096221923828
Cycle #28: mean_squared_error 26.538833618164062
Cycle #29: mean_squared_error 35.586570739746094
Cycle #30: mean_squared_error 35.999725341796875
Cycle #31: mean_squared_error 37.7243537902832
Cycle #32: mean_squared_error 28.9063720703125
Cycle #33: mean_squared_error 33.94091033935547
Cycle #34: mean_squared_error 31.919336318969727
Cycle #35: mean_squared_error 39.326290130615234
Cycle #36: mean_squared_error 32.05040740966797
Cycle #37: mean_squared_error 37.17812728881836
Cycle #38: mean_squared_error 35.16141891479492
Cycle #39: mean_squared_error 31.629375457763672
Cycle #40: mean_squared_error 34.310123443603516
Cycle #41: mean_squared_error 42.37334442138672
Cycle #42: mean_squared_error 33.280670166015625
Cycle #43: mean_squared_error 36.87359619140625
Cycle #44: mean_squared_error 34.897403717041016
Cycle #45: mean_squared_error 35.6600341796875
Cycle #46: mean_squared_error 30.58363914489746
Cycle #47: mean_squared_error 30.675426483154297
Cycle #48: mean_squared_error 34.59047317504883
Cycle #49: mean_squared_error 29.703136444091797
Cycle #50: mean_squared_error 35.65740203857422

In [17]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 50.596184997558595
The standard deviation of the mean squared errors: 61.60791616836794

##### The mean of the mean squared errors from Case B is slight lower compared to Case A, however it seems like data normalization do not contribute much as errors in both A and B are still considered high.

#### **C. Increate the number of epochs - repeating Part B with 100 epochs**

In [18]:
# Create a model
model_3 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model_3.compile(optimizer='adam', loss='mean_squared_error')

In [19]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Splitting data into training set and test set
    X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3)
    #Train and test the model at the same time
    res = model_3.fit(X_train, y_train, epochs=100, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 159.4805450439453
Cycle #2: mean_squared_error 99.79444122314453
Cycle #3: mean_squared_error 75.74494171142578
Cycle #4: mean_squared_error 74.35004425048828
Cycle #5: mean_squared_error 58.27476119995117
Cycle #6: mean_squared_error 50.24244689941406
Cycle #7: mean_squared_error 47.843360900878906
Cycle #8: mean_squared_error 45.58302688598633
Cycle #9: mean_squared_error 45.47398376464844
Cycle #10: mean_squared_error 48.722530364990234
Cycle #11: mean_squared_error 46.84992218017578
Cycle #12: mean_squared_error 40.91883850097656
Cycle #13: mean_squared_error 46.4486083984375
Cycle #14: mean_squared_error 47.10515594482422
Cycle #15: mean_squared_error 40.302154541015625
Cycle #16: mean_squared_error 47.984275817871094
Cycle #17: mean_squared_error 40.21487045288086
Cycle #18: mean_squared_error 45.738502502441406
Cycle #19: mean_squared_error 36.517818450927734
Cycle #20: mean_squared_error 49.08242416381836
Cycle #21: mean_squared_error 51.21449661254883
Cycle #22: mean_squared_error 42.546295166015625
Cycle #23: mean_squared_error 33.95146942138672
Cycle #24: mean_squared_error 54.24877166748047
Cycle #25: mean_squared_error 40.820594787597656
Cycle #26: mean_squared_error 41.979583740234375
Cycle #27: mean_squared_error 42.35603713989258
Cycle #28: mean_squared_error 48.54840850830078
Cycle #29: mean_squared_error 40.024147033691406
Cycle #30: mean_squared_error 45.821449279785156
Cycle #31: mean_squared_error 47.37114715576172
Cycle #32: mean_squared_error 40.87662124633789
Cycle #33: mean_squared_error 46.481597900390625
Cycle #34: mean_squared_error 42.12813186645508
Cycle #35: mean_squared_error 42.64480209350586
Cycle #36: mean_squared_error 44.7201042175293
Cycle #37: mean_squared_error 36.72685241699219
Cycle #38: mean_squared_error 40.16495132446289
Cycle #39: mean_squared_error 39.43628692626953
Cycle #40: mean_squared_error 39.452205657958984
Cycle #41: mean_squared_error 40.7589225769043
Cycle #42: mean_squared_error 42.81871032714844
Cycle #43: mean_squared_error 42.02119064331055
Cycle #44: mean_squared_error 51.251102447509766
Cycle #45: mean_squared_error 40.36301040649414
Cycle #46: mean_squared_error 41.206111907958984
Cycle #47: mean_squared_error 43.43570327758789
Cycle #48: mean_squared_error 46.597957611083984
Cycle #49: mean_squared_error 44.81172561645508
Cycle #50: mean_squared_error 42.90162658691406

In [20]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 48.88705337524414
The standard deviation of the mean squared errors: 19.072192367588524

##### There is a slight decrease in Case C comparing to Case B. However the result is not significant enough, it seems like increasing the numbers of epochs does not contribute much as the errors for both cases is still consider quite high.

#### **D. Increase the number of hidden layers - repeating part B with 3 hidden layers, each of 10 nodes and ReLU activation function.**

In [21]:
# Create a model
model_4 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model_4.compile(optimizer='adam', loss='mean_squared_error')

In [22]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Splitting data into training set and test set
    X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3)
    #Train and test the model at the same time
    res = model_4.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 100.92414855957031
Cycle #2: mean_squared_error 61.28036880493164
Cycle #3: mean_squared_error 50.937904357910156
Cycle #4: mean_squared_error 43.54908752441406
Cycle #5: mean_squared_error 37.81708908081055
Cycle #6: mean_squared_error 32.360015869140625
Cycle #7: mean_squared_error 37.070823669433594
Cycle #8: mean_squared_error 32.59604263305664
Cycle #9: mean_squared_error 29.07569694519043
Cycle #10: mean_squared_error 35.336334228515625
Cycle #11: mean_squared_error 30.933639526367188
Cycle #12: mean_squared_error 31.914108276367188
Cycle #13: mean_squared_error 33.102760314941406
Cycle #14: mean_squared_error 32.133541107177734
Cycle #15: mean_squared_error 28.380245208740234
Cycle #16: mean_squared_error 25.636995315551758
Cycle #17: mean_squared_error 23.91638946533203
Cycle #18: mean_squared_error 23.075387954711914
Cycle #19: mean_squared_error 24.63487434387207
Cycle #20: mean_squared_error 27.722440719604492
Cycle #21: mean_squared_error 25.517988204956055
Cycle #22: mean_squared_error 23.84873390197754
Cycle #23: mean_squared_error 21.990859985351562
Cycle #24: mean_squared_error 23.50701904296875
Cycle #25: mean_squared_error 21.546323776245117
Cycle #26: mean_squared_error 21.437925338745117
Cycle #27: mean_squared_error 22.740718841552734
Cycle #28: mean_squared_error 20.072284698486328
Cycle #29: mean_squared_error 21.55318260192871
Cycle #30: mean_squared_error 21.030305862426758
Cycle #31: mean_squared_error 24.39821434020996
Cycle #32: mean_squared_error 22.89322280883789
Cycle #33: mean_squared_error 22.594165802001953
Cycle #34: mean_squared_error 23.70051383972168
Cycle #35: mean_squared_error 21.565792083740234
Cycle #36: mean_squared_error 20.372692108154297
Cycle #37: mean_squared_error 22.306184768676758
Cycle #38: mean_squared_error 18.140443801879883
Cycle #39: mean_squared_error 24.039255142211914
Cycle #40: mean_squared_error 20.02520179748535
Cycle #41: mean_squared_error 17.179752349853516
Cycle #42: mean_squared_error 20.819978713989258
Cycle #43: mean_squared_error 23.561664581298828
Cycle #44: mean_squared_error 23.595033645629883
Cycle #45: mean_squared_error 20.152456283569336
Cycle #46: mean_squared_error 18.57625389099121
Cycle #47: mean_squared_error 21.613603591918945
Cycle #48: mean_squared_error 21.726322174072266
Cycle #49: mean_squared_error 23.15180015563965
Cycle #50: mean_squared_error 17.727096557617188

In [23]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 27.875657691955567
The standard deviation of the mean squared errors: 13.341021901136477

##### It is obvious that Case D has the lowest mean of the mean squared errors compared to the rest of the cases. This shows that additional layers holds the highest potential and its importance in lowering the errors comparing to other tuning methods. Further the comparisons of the previous cases i.e Case A, B and C proven that comparison using neural network with only one hidden layer may not be the best suggestion as it might produce poor and unpredictable result.